### ISSUE TITLE
Update Readme.md at root of repository 

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#102]
Lets remove existing stuff and put details on how to use this repository.

**Comment by relentless-pursuit** [comment]
as in remove the readme.md we added?

**Comment by romani** [comment]
Please rephrase question, I don't understand it.

**Comment by relentless-pursuit** [comment]
i didn't get `Lets remove existing stuff`.

**Comment by romani** [comment]
Remove existing content of https://github.com/checkstyle/test-configs/blob/main/README.md
