### ISSUE TITLE
CI is enforced over java code to demand basic code quality

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#107]
We need to apply checkstyle/pmd/spotbug/forbidden-api/ over all java projects of this repo.
Configs should be taken from main repo https://github.com/checkstyle/checkstyle/
We can relax Javadoc rules as we do not need it there, such projects are not a public library. 

~if we have time: we should try Idea Inspections validation.~

**Comment by romani** [comment]
We need checkstyle to be activated

**Comment by relentless-pursuit** [comment]
> We need checkstyle to be activated

It is activated. 

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
        "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
        <module name="UnusedImports"/>
        <module name="AvoidStarImport"/>
    </module>
</module>
```

**Comment by romani** [comment]
Please add all modules in config https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle-checks.xml

**Comment by romani** [comment]
At https://github.com/checkstyle/test-configs/blob/main/extractor/config/pmd/pmd-ruleset.xml
Please activate all excluded , example of config that we have in main repository https://github.com/checkstyle/checkstyle/blob/master/config/pmd-main.xml

**Comment by relentless-pursuit** [comment]
> At https://github.com/checkstyle/test-configs/blob/main/extractor/config/pmd/pmd-ruleset.xml Please activate all excluded , example of config that we have in main repository https://github.com/checkstyle/checkstyle/blob/master/config/pmd-main.xml

I have excluded on purpose. They At https://github.com/checkstyle/test-configs/blob/main/extractor/config/pmd/pmd-ruleset.xml were affecting the logic.

**Comment by romani** [comment]
>were affecting the logic.

Yes, and we need to change logic to be more maintainable by other. Such rules will guide in right direction. Or some of them will be excluded with explanation of why we should not use the, each exclude should have explicit explanation.

**Comment by romani** [comment]
@relentless-pursuit 

I added checkstyle to project, with all Checks as disabled, https://github.com/checkstyle/test-configs/commit/4b55f76ac9c7c25aa55f9519776ea9867d9403b6

please remove check from suppression and fix violation and send PR.
Please do not make big PRs, select few Checks and fix them in single PR. So we expect about ~10 PRs to fix all violations.

**Comment by romani** [comment]
Reopening to double check that we are in good spot.

We need to check same over diff tool also

**Comment by romani** [comment]
@relentless-pursuit , please update CI to do `./gradlew build`

and add build of https://github.com/checkstyle/test-configs/tree/main/diff-java-tool
and add this pack of tools in diff-java-tool.
