### ISSUE TITLE
new config template

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#117]
https://github.com/checkstyle/contribution/pull/877#issuecomment-2226939306

**Comment by relentless-pursuit** [comment]
@Romani i see new properties being created just after treewalker. Does it mean, the format shall have these properties? I guess i have to change code. 

https://github.com/mahfouz72/contribution/blob/70f2f5b9907760e029b808656c2de0e2248cdd6c/checkstyle-tester/my_check.xml

**Comment by romani** [comment]
I do not see anything to be changed. your PR is good.
