### ISSUE TITLE
Test all-in-one bundles 

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#120]
After initial implementation of new workflow is done by `Github, generate report for`

We need to test all bundles to make sure that report generation can be finished.

Expected problems: oom errors due to numerous violations or timeouts.

If any problem detected, we need to reduce amount of projects to let report to finish.

PR to https://github.com/checkstyle-gsoc/checkstyle/pull/28

**Comment by romani** [comment]
We have a lot of bundles, so triggering should be done from phone on the go, not a laptop time.

**Comment by romani** [comment]
@relentless-pursuit , please confirm that you can test all bundles in your organization.

While we waiting for merge in main repository, we can reuse your org and simply get all bundles be tested (just to make sure reports can successfully finish).

If yes, please start. I will join.
We can have single PR for one Check.

**Comment by romani** [comment]
We should start from running all-in-one first.
If it pass it means all others will pass for sure.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit , please confirm that you can test all bundles in your organization.
> 
> While we waiting for merge in main repository, we can reuse your org and simply get all bundles be tested (just to make sure reports can successfully finish).
> 
> If yes, please start. I will join. We can have single PR for one Check.

@romani i don't mind testing but wouldn't it be great if we could test it in main repo. because, we already have a mechanism of backwards compatability, not that the merge will hinder the existing regression testing. But, if we do testing and it can be a tough task to test all 180 checks, how can we evaluate better if not done on a main repo?

**Comment by romani** [comment]
>wouldn't it be great if we could test it in main repo.

Yes, but it would not be quicker. 
Moreover, it will use GitHub quotes of execution, so we will make huge queue and we will slow down all others.
In your org, you have more freedom and isolation.
We will test not a workflow , but ability of reports to finish, no timeouts.

>But, if we do testing and it can be a tough task to test all 180 checks

Not though, just a bit long, but we can start now, and until September trigger 180 executions for all-in-one. 
I will help to trigger from phone, as you already did all (except for one issue ) so convenient that it takes less 1 minutes to trigger.

**Comment by relentless-pursuit** [comment]
### PR Checklist

#### Modules (Compilable)
- [X] annotation
- [X] arraytypestyle
- [X] avoidescapedunicodecharacters
- [X] blocks
- [X] coding
- [X] descendanttoken
- [X] design
- [X] finalparameters
- [X] header
- [X] imports
- [X] indentation
- [X] javadoc
- [X] metrics
- [X] modifier
- [X] naming
- [X] newlineatendoffile
- [X] nocodeinfile
- [X] orderedproperties
- [X] outertypename
- [X] regexp
- [X] sizes
- [X] todocomment
- [X] trailingcomment
- [X] translation
- [X] uncommentedmain
- [X] uniqueproperties
- [X] upperell
- [X] whitespace
- [X] filefilters
- [] filters - we will not cover filters as part on this project, they are too complicated 

#### Modules (Non-Compilable)
- [X] annotation
- [X] coding
- [X] naming
- [X] size
- [X] whitespace

**Comment by relentless-pursuit** [comment]
is this required?

**Comment by romani** [comment]
Yes, as I already noticed RegexpHeader is not working and few others

**Comment by romani** [comment]
Testing is finished at https://github.com/checkstyle-gsoc/checkstyle/pull/30#issuecomment-2379593405

All failed config will be handled at https://github.com/checkstyle/test-configs/issues/141
