### ISSUE TITLE
new project list template

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/test-configs#123]
please remember as we merge https://github.com/checkstyle/contribution/pull/878 we may need to update this repo with the new content of `projects-to-test-on-for-github-action.properties`

**Comment by relentless-pursuit** [comment]
> please remember as we merge [checkstyle/contribution#878](https://github.com/checkstyle/contribution/pull/878) we may need to update this repo with the new content of `projects-to-test-on-for-github-action.properties`

The PR is up for merger. Thank you for creating the issue.

**Comment by mahfouz72** [comment]
> The PR is up for merger.

Thank you, then this can be closed
