### ISSUE TITLE
Some config results in OOM, reduce list of project in config 

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#141]
While testing regression testing of WhitespaceAround Check, we realised it led to OOM issue. We need to see which projects can be removed to keep it light weight. 

Full list at https://github.com/checkstyle/test-configs/issues/120#issuecomment-2241202788

**Comment by relentless-pursuit** [comment]
@romani How to investigate?

**Comment by romani** [comment]
Just remove projects from list until it pass :)

**Comment by romani** [comment]
in referenced PR, they will split config in few, they will probably put jdk in separate config.
so we can do the same and just drop openjdk from list of projects for all-in-one.

**Comment by romani** [comment]
regexp still has problems https://github.com/checkstyle/checkstyle/pull/15578#issuecomment-2406544640

**Comment by relentless-pursuit** [comment]
-- []Header
IllegalTokenText
InterfaceMemberImpliedModifier
MultipleStringLiterals
NeedBraces
RegexpHeader
Regexp
TrailingComment

**Comment by relentless-pursuit** [comment]
For IllegalTokenText and MultipleStringLiterals, we made changes for the configs to be correct in the extractor. Earlier, we noticed there was a difference wrt how configs from main repo of checkstyle and the generated ones had wrt quotes. We saw double quotes being wrapped under value. We made code changes to make it single quotes complying with the examples files in main repo in this PR: https://github.com/checkstyle/test-configs/pull/212

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11305582825/job/31445261771

Github, generate report for InterfaceMemberImpliedModifier/all-examples-in-one

The results were successful. 

Doing a second round of testing in main repo. Runner: https://github.com/checkstyle/checkstyle/actions/runs/11305872027

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11305891527

Github, generate report for NeedBraces/all-examples-in-one

The results were successful.

Doing a second round of testing in main repo. Runner: https://github.com/checkstyle/checkstyle/actions/runs/11306157786

**Comment by relentless-pursuit** [comment]
For TrailingComment, 
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/11309536077/job/31453494011

Despite deleting the project list of openjdk21, checkstyle-sonar my the execution is stuck. 
@romani, i am not being able to figure out the reason as the logs don't say anything.

**Comment by relentless-pursuit** [comment]
For regex, we had to create a PR to make sure generated configs are i sync with actual xml configs in example files. 

Test run: https://github.com/checkstyle/checkstyle/actions/runs/11310865938
