### ISSUE TITLE
On cancel or failing of job 

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#147]
https://stackoverflow.com/a/74690897/1015848

Is this approach can work if job is cancelled by concurrency?

If yes, it will be awesome to put :( emoji on comment

**Comment by relentless-pursuit** [comment]
@romani I am confused of the requirement. After reading the stackoverflow, the requirement there is parallel jobs should fail. But, we in the workflow have a sequential flow. Then, what is the need? Apart from that, is the requirmeent to make a sad emoji if job fails by concurrency?

**Comment by romani** [comment]
If job is failing put sad emojis.
But I am not sure if cancel is a failure.

**Comment by relentless-pursuit** [comment]
We can close this.

**Comment by relentless-pursuit** [comment]
> If job is failing put sad emojis. But I am not sure if cancel is a failure.

I have just used sad emoji for cancel and not failure. Both are different according to me. for isntance, if i start a concurrent workflow run, the old gets cancelled. But, if i try to trigger the workflow on a closed or inactive PR, the workflow is failed. And, won't give sad emoji.

**Comment by romani** [comment]
We merged few PRs that are linked to https://github.com/checkstyle/checkstyle/issues/15412
