### ISSUE TITLE
extractor: handle xml  type of inlined configs in Inputs

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#156]
Input files that have 
```
/*xml
 
```

**Comment by relentless-pursuit** [comment]
Can we close this issue?

**Comment by romani** [comment]
Let me show prove of testing before closing

**Comment by romani** [comment]
Let me show prove of testing before closing

**Comment by romani** [comment]
example of xml https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
i am not sure of the issue, but i thought it is running the workflow with xml.

**Comment by relentless-pursuit** [comment]
I think extractor is already doing that. It parses the xml contents from the example files to generate configs. @romani please let me know if i am missing anything.

**Comment by romani** [comment]
@relentless-pursuit , please show example of xml config in checkstyle repo and resulted folder in test-configs repository

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/annotation/annotationusestyle/Example3.java
extracted to
https://github.com/checkstyle/test-configs/blob/main/AnnotationUseStyle/Example3/config.xml
