### ISSUE TITLE
test all configs that we created in main repo by 'Github, generate report'

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#16]
some example: https://github.com/checkstyle/checkstyle/pull/14924

but there is more quick and easy for CI approach.

get latest(I pushed with force changes to it few minutes before creation of this issue) branch `all-ci-disabled` to your fork , in main repo it is at https://github.com/checkstyle/checkstyle/tree/all-ci-disabled 

create a PR for your forked  `all-ci-disabled` to master branch on upstream repo https://github.com/checkstyle/checkstyle/tree/master
it will simply block all(most CI) from execution.
So we will not waste CI time on any validation.

https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#executing-generation

after that update PR description with links to testing configs, example:
`Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/config.xml`

`Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/SummaryJavadoc/Example1/list-of-projects.properties`

wait for report to be generated.
We need to test that all configs that we are created https://github.com/checkstyle/test-configs are executable and produce no diff, as we did not change anything in  `all-ci-disabled`.
All configs should be tested to make sure CI can finish on such Check config and such big list of projects.
Please record somewhere time of execution for CI job for each config.

**Comment by romani** [comment]
@relentless-pursuit , I removed more gitub  workflows from `all-ci-disabled` in main repo, and pushed with force, please pull it.

**Comment by romani** [comment]
@relentless-pursuit , please continue testing, to let me see that you understand how to run testing of workflow.

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/pull/14931 SummaryJavadoc testing

**Comment by romani** [comment]
@relentless-pursuit , please finish testing for abbareviation in separate PR and we can close this issue.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit , please finish testing for abbareviation in separate PR and we can close this issue.

Sure

**Comment by relentless-pursuit** [comment]
@Romani https://github.com/checkstyle/checkstyle/pull/14935. I guess it is done.

**Comment by romani** [comment]
Ok, all configs created manually are working well and ready to use by others

**Comment by romani** [comment]
Please test all-examples for both Checks.
This config will be also generated.
