### ISSUE TITLE
trigering regresion-report.yml on closed PR respond with comment

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#166]
detected at https://github.com/checkstyle/checkstyle/pull/15525#issuecomment-2313930015

can we not respond to such comments at all ? consider it as not a trigger at all

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/actions/runs/10657459606

This is the runner invoked upon the comment of the closed PR. 

<img width="988" alt="image" src="https://github.com/user-attachments/assets/e330a77a-b9b9-4515-9049-382a2fe91e83">

https://github.com/checkstyle/checkstyle/pull/15576#issuecomment-2323501695

No comment was passed in the PR. 

@Romani
