### ISSUE TITLE
regression-report.yml does not post comment with report

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#167]
triggered at https://github.com/checkstyle/checkstyle/pull/15558#issuecomment-2314205302
action execution at https://github.com/checkstyle/checkstyle/actions/runs/10590083501/job/29346499043

one more example: https://github.com/checkstyle/checkstyle/pull/14882#issuecomment-2314149355
execution: https://github.com/checkstyle/checkstyle/actions/runs/10589849075

same problem twice.

**Comment by relentless-pursuit** [comment]
https://github.com/checkstyle/checkstyle/pull/15576#issuecomment-2321221142

<img width="811" alt="image" src="https://github.com/user-attachments/assets/fbde1d24-4e01-4820-b4d5-7913b676fb27">

This issue was resolved and tested in the PR: https://github.com/checkstyle/checkstyle/pull/15576
