### ISSUE TITLE
Add jar execution to the existing workflow for DiffTool.java

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#185]
We need to add a step to execute the jar of DiffTool.java

We need to create ready to use config.xml file and projects.property file (all files can be stored in special folder in repo to be used just by reference to them).
config.xml will have any check
projects.property will have reference to code of this reporsitory
patch-diff-report-tool will be downloaded by action.

result diff report will be empty, but it is ok, all we need is fact that execution is not failing with exceptions or any other error.

Ideally we should do few runs to cover most used modes of execution.
and all arguments should be used at least ones - https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#command-line-arguments

We should have bad argument execution to print help.
We should have at least 3 executions that we use:
https://github.com/checkstyle/checkstyle/blob/155b69e71569679219ac91db10e216c896bb7b14/.github/workflows/regression-report.yml#L510-L525

**Comment by romani** [comment]
fix is merged
