### ISSUE TITLE
New format for readme.md

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#198]
# Example1 Configs

Bellow are two options that will do the same but use different versions
of github actions in checkstyle repository.

### Option 1
Trigger report generation by comment in Pull Request:
```
Github, generate report for AbbreviationAsWordInName/Example1
```

### Option 2

Paste below given to PR description to use such test configs:
```
Report label: AbbreviationAsWordInName/Example1
Diff Regression config: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example1/config.xml
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/test-configs/main/AbbreviationAsWordInName/Example1/list-of-projects.properties
```

Trigger report generation by comment in Pull Request:
```
Github, generate report
```
or as alternative by comment
```
Github, generate report for configs in PR description
```

**Comment by romani** [comment]
Wording can be changed. It is just structure.

**Comment by romani** [comment]
@mahfouz72, fyi.

**Comment by mahfouz72** [comment]
Thanks. What about this new trigger comment https://github.com/checkstyle/checkstyle/pull/15578#issuecomment-2335053090? I am not sure if we(users) will use it or it is just will be triggered automatically on new input. Do we need to include it in the README?

**Comment by romani** [comment]
> Github, generate report by config from

it is feature of https://github.com/checkstyle/checkstyle/blob/master/.github/workflows/regression-report.yml and specific to PR 
this repository does not know where configs will be used, configs can be used by any github workflow.

discussion on how to document github workflow to use Input from PR is at https://github.com/checkstyle/checkstyle/issues/15380
still waiting for maintainers to give feedback, while no feedback, we keep polishing implementation.
