### ISSUE TITLE
Create special RequireThis configs with custom set of projects

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#20]
We should have a kind of global properties list, where we can dump projects to be tested. These not beed part of specific module folders as most users might not be using it. 

https://checkstyle.org/checks/coding/requirethis.html#RequireThis

we need to make sure that
https://github.com/checkstyle/contribution/blob/d85c3ddc6ae531dc372b83509be88a1b15b86ac3/checkstyle-tester/projects-to-test-on-for-github-action.properties#L40-L41 
is in testing scope
we do not have it at https://github.com/checkstyle/test-configs/blob/main/extractor/src/main/resources/all-projects.properties
so lets create special list of projects for this Check.

**Comment by romani** [comment]
our extractor application will have somewhere config that define list of projects to place in result project files.
so we should expect have something like:
generic set of project, Check specific set of projects, Check-config specific set of projects.

> Check-config specific set of projects.

example is japan period for Summaryjavadoc.

**Comment by nrmancuso** [comment]
Few things:
 - I am not clear on how this will be used
 - We need to clearly define the format here before work begins

**Comment by romani** [comment]
@relentless-pursuit , please send PR for RequiredThis it looks like need special set of projects too.

**Comment by romani** [comment]
@relentless-pursuit , please add new project to this Check only to all bundles.

**Comment by romani** [comment]
Resolved by https://github.com/checkstyle/test-configs/pull/112
