### ISSUE TITLE
add manually all configs that we plan for AbbreviationAsWordInName

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#3]
before 
https://github.com/checkstyle/test-configs/issues/1

lets quickly manually create all configs to be aligned on layout and names
and in issue #1 we will simply replace them by generated approach content will be mostly the same (only minor formatting might be different).

test resulted configs in main repo by "GitHub, generate report"

**Comment by romani** [comment]
@relentless-pursuit , please do this issue with high priority.
to make final state a bit more visual.

**Comment by relentless-pursuit** [comment]
@Romani, i keep getting confused on this. Initially, I thought we had to create hardcoded configs like below extracted from examples of xml in checkstyle repo like below. 

```
<module id="config1" name="AnnotationLocation">
</module>

<module id="config2" name="AnnotationLocation">
<property name="allowSamelineSingleParameterlessAnnotation"
          value="false"/>
<property name="allowSamelineParameterizedAnnotation" value="false"/>
<property name="allowSamelineMultipleAnnotations" value="true"/>
</module>

<module id="config3" name="AnnotationLocation">
<property name="allowSamelineMultipleAnnotations" value="false"/>
<property name="allowSamelineSingleParameterlessAnnotation"
          value="false"/>
<property name="allowSamelineParameterizedAnnotation" value="true"/>
</module>

<module id="config4" name="AnnotationLocation">
<property name="tokens" value="METHOD_DEF"/>
<property name="allowSamelineMultipleAnnotations" value="false"/>
<property name="allowSamelineSingleParameterlessAnnotation"
          value="true"/>
<property name="allowSamelineParameterizedAnnotation" value="false"/>
</module>
```

But, after the groovy script, I assumed once a user mentions a module name, my github action checks out to test-config and then executes the generateConfig.groovy. And, the idea of the script is to parse the xml taking moduleName and config-type (i mean example number) and create a repo. And, post the link of the repo back to the PR of the user wanting regression testing.

**Comment by romani** [comment]
> But, after the groovy script, I assumed once a user mentions a module name, my github action checks out to test-config and then executes the generateConfig.groovy. 

no, application in this repo, generates configs and confgs are commited to this repo and ready for use as plain text.
Github action will use already generated files for first milestone.
at the end will do some config genration in github action worflow, but lets not focus on this now.

**Comment by relentless-pursuit** [comment]
Please hava a look @romani
