### ISSUE TITLE
Creating configs Package wise

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#52]
#### Modules (Compilable)
- [X] annotation
- [X] arraytypestyle
- [X] avoidescapedunicodecharacters
- [X] blocks
- [X] coding
- [X] descendanttoken
- [X] design
- [X] finalparameters
- [X] header
- [X] imports
- [X] indentation
- [X] javadoc
- [X] metrics
- [X] modifier
- [X] naming
- [X] newlineatendoffile
- [X] nocodeinfile
- [X] orderedproperties
- [X] outertypename
- [X] regexp
- [X] sizes
- [X] todocomment
- [X] trailingcomment
- [X] translation
- [X] uncommentedmain
- [X] uniqueproperties
- [X] upperell
- [X] whitespace
- [X] filefilters
- [] filters - we will not cover filters as part on this project, they are too complicated 

#### Modules (Non-Compilable)
- [X] annotation
- [X] coding
- [X] naming
- [X] size
- [X] whitespace

**Comment by relentless-pursuit** [comment]
### PR Checklist

#### Modules
- [X] annotation
- [ ] arraytypestyle
- [ ] avoidescapedunicodecharacters
- [X] blocks
- [ ] coding
- [ ] descendanttoken
- [ ] design
- [ ] finalparameters
- [ ] header
- [ ] imports
- [ ] indentation
- [ ] javadoc
- [ ] metrics
- [ ] modifier
- [ ] naming
- [ ] newlineatendoffile
- [ ] nocodeinfile
- [ ] orderedproperties
- [ ] outertypename
- [ ] regexp
- [ ] sizes
- [ ] todocomment
- [ ] trailingcomment
- [ ] translation
- [ ] uncommentedmain
- [ ] uniqueproperties
- [ ] upperell
- [ ] whitespace
- [ ] filefilters
- [ ] filters

**Comment by romani** [comment]
@relentless-pursuit , pease content of comment above to issue description to ease finding of it.

**Comment by romani** [comment]
Let's consider all is done
