### ISSUE TITLE
Make changes to ConfigSerializer to handle Checks without Treewalker, ex: Header check

### ISSUE THREAD

**Issue by relentless-pursuit** [checkstyle/test-configs#55]
We need to make changes to the code base to be able to generate configs for checks without Treewalker as immediate parent node.

**Comment by romani** [comment]
Keep in mind it is just matter on separate template xml for config with placeholder to search-replace.

**Comment by romani** [comment]
https://github.com/checkstyle/test-configs/pull/82#discussion_r1653657463 should be done
