### ISSUE TITLE
Put in README.md example of trigger for new workflow 

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#96]
"or make comment in PR:"
`Github, generate report for SummaryJavadoc/Example1`

From https://github.com/checkstyle/test-configs/blob/1e98f67239a38c969893ef095b5026a4ad42a6d2/SummaryJavadoc/Example1/README.md

Should be added when we have new workflow.

**Comment by relentless-pursuit** [comment]
Is the issue still valid? But, now how do i test workflows. I had created few workflows in some repo as suggested by nrmacunso. But, is there a way to test my cahnges on diff.groovy if i push changes from master branch to main repo?

**Comment by romani** [comment]
This issue is for a time when we create new workflow or we update existing workflow to trigger by new phrase.

**Comment by romani** [comment]
To test workflows, you need to create your own repository copy workflow to it, and make PRs to your own repository and see how it runs in logs.

**Comment by romani** [comment]
All changes should be above this line https://github.com/checkstyle/checkstyle/blob/947002a3d66557d7e62a5aee81c7de449ce5f168/.github/workflows/diff-report.yml#L88

**Comment by relentless-pursuit** [comment]
@romani created a PR: https://github.com/checkstyle/checkstyle/pull/15232/files

And, also test undergoing in new organisation with checkstyle forked:
https://github.com/checkstyle-gsoc/checkstyle/actions/runs/9882698081/job/27296080180

**Comment by romani** [comment]
It would be awesome if action workflow will do a comment if there was some error in handling request.

**Comment by relentless-pursuit** [comment]
> It would be awesome if action workflow will do a comment if there was some error in handling request.
> Ideally post link to action execution log to comments.

We can. Here is the link for the PR used for testing. Pardon me it is quite messy. I had created this org and sent inviation. I am not sure if you have accepted the invitation or not. 

https://github.com/checkstyle-gsoc/checkstyle/pull/2

also, adding the link to workflow. 
https://github.com/checkstyle-gsoc/checkstyle/blob/master/.github/workflows/experiment-automate-regression.yml

The only change in workflow is the report name, my AWS account and some repo change as i am doing under my org. Hence, had to tweak the workflow to understand my forked branches.

**Comment by romani** [comment]
@relentless-pursuit , please keep in mind that new workflow not this issue it is https://github.com/checkstyle/test-configs/issues/103 .

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit , please keep in mind that new workflow not this issue it is #103 .

shall i directly proceed for the above issue as it seems to me that this issue has less tangible benefits?

**Comment by romani** [comment]
Yes, this issue should be done after #103
